### ISSUE TITLE
Can't read a Json file

### ISSUE THREAD

**Issue by Sokakaoh** [jtablesaw/tablesaw#768]
Hi,

I wanted to use package to read json file as Pandas do for Python. I tried to read it with : 
```
Table dataJsonDashboard = Table.read().usingOptions(JsonReadOptions.builder("/Path/to/File");
OR
Table dataJsonDashboard = Table.read().file("/Path/to/File");
```
But when i use one of this solution, i get this message error 
```
Exception in thread "main" java.lang.IllegalStateException: Only reading a json array or arrays or objects is currently supported
```
How should I solve this error?  I'm using the latest version.

Thanks

**Comment by benmccann** [comment]
Can you share the file? If not, what is the format of the file?

**Comment by Sokakaoh** [comment]
Thanks for your quick reply. I tried with a very simple json like that.
```
{
    "test": {
        "test1": 12
    }
}

```

**Comment by benmccann** [comment]
And what do you expect to happen in that case?

Tablesaw is meant to hold tabular data. That input doesn't seem tabular, so I'm not sure how we'd handle it. I'd recommend making it into an array of objects - then we will will have a row for each object.

The exception message "Only reading a json array or arrays or objects is currently supported" was mean to say "Only reading a json array of arrays or objects is currently supported". I just fixed that so that it now says "Only reading a JSON array is currently supported. The array must hold an array or object for each row."

**Comment by Sokakaoh** [comment]
Sorry for this late answer. 

And what if you have data like this ?  
```
"dossiers":[
    {
      "titre":"test1",
      "error":5,
      "success":10
    },
    {
      "titre":"test2",
      "error":10,
      "success":5
  }
  ]
}
```

You are not supposed to have a array like this ? Because i tried with this data and i still have the same message.
  titre    |  error  |  success
  test1  |    5    |   10
  test2  |   10    |   5

**Comment by benmccann** [comment]
Just remove `"dossiers":`

**Comment by Sokakaoh** [comment]
Ok, Ididn't think it worked like that. I will just work before on my json to have a good format. 
Thanks a lot
